coverage:
  # See https://docs.codecov.io/docs/commit-status
  status:
    project:
      default: false
      client:
        paths: "connector/"
        threshold: 2% # don't allow coverage to drop on client
      service:
        paths: "core"
        threshold: 2% # allow coverage to drop on service by 2% (wip)
ignore:
  - "example/**"
